// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Branch.Workspaces.Plugin
{
    internal sealed partial class Vsix
    {
        public const string Id = "Branch.Workspaces.2821b40b-af2e-48f4-bc33-8908c3980e1b";
        public const string Name = "Branch Workspaces";
        public const string Description = @"A VisualStudio extension to provide branch based workspace handling";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Danny Schneider";
        public const string Tags = "";
    }
}
